# Generated by Django 2.2.4 on 2019-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='export_date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
