# Generated by Django 2.2.4 on 2019-09-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('td_export', '0003_auto_20190903_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportfile',
            options={},
        ),
        migrations.AddField(
            model_name='exportfile',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
